from django.db import models

class CityChoices(models.TextChoices):
    TEHRAN = ('tehran', 'تهران')
    MASHHAD = ('mashhad', 'مشهد')
    ISFAHAN = ('isfahan', 'اصفهان')
    TABRIZ = ('tabriz', 'تبریز')
    SHIRAZ = ('shiraz', 'شیراز')
    AHVAZ = ('ahvaz', 'اهواز')
    KERMANSHAH = ('kermanshah', 'کرمانشاه')
    RASHT = ('rasht', 'رشت')
    KARAJ = ('karaj', 'کرج')
    QOM = ('qom', 'قم')
    YAZD = ('yazd', 'یزد')
    ORUMIEH = ('orumiyeh', 'ارومیه')
    KHORRAMSHAHR = ('khorramshahr', 'خرمشهر')
    SANANDAJ = ('sanandaj', 'سنندج')
    ARAK = ('arak', 'اراک')
    QAZVIN = ('qazvin', 'قزوین')
    BANDAR_ABAS = ('bandar_abbas', 'بندرعباس')
    ZAHEEDAN = ('zahedan', 'زاهدان')
    KERMAN = ('kerman', 'کرمان')
    SARI = ('sari', 'ساری')
    BIRJAND = ('birjand', 'بیرجند')
    BOJNURD = ('bojnurd', 'بجنورد')
    GORGAN = ('gorgan', 'گرگان')
    ZANJAN = ('zanjan', 'زنجان')
    KASHAN = ('kashan', 'کاشان')
    LAMARD = ('lamerd', 'لامرد')
    DEZFUL = ('dezful', 'دزفول')
    BABOL = ('babol', 'بابُل')
    ARDEBIL = ('ardebil', 'اردبیل')
    SHAHRKORD = ('shahrekord', 'شهرکرد')
    NAIN = ('nain', 'نایین')
    MIANDEH = ('miandeh', 'میاندوآب')
    SAQQEZ = ('saqqez', 'سقز')
    JAHROM = ('jahrom', 'جهرم')
    FERDOUS = ('ferdows', 'فردوس')
    BANDAR_GHALEH = ('bandarghaleh', 'بندر قله')
    GONBAD_E_KAVUS = ('gonbad_e_kavus', 'گنبد کاووس')
    MARAMSAR = ('maramsar', 'مرامسار')
    BAKHTAR = ('bakhtar', 'بختار')
    KASHMAR = ('kashmar', 'کاشمر')
    ZADEGAN = ('zadegan', 'زاهدگان')
    SABZEVAR = ('sabzevar', 'سبزوار')
    NEISHABUR = ('neishabur', 'نیشابور')
    FIRUZABAD = ('firuzabad', 'فیروزآباد')
    BAKHTIARI = ('bakhtiari', 'بختیاری')



class User(models.Model):
    username = models.CharField(max_length=32, unique=True)
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    birthdate = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    bio = models.TextField(blank=True)
    city = models.CharField(max_length=20, choices=CityChoices.choices, default=CityChoices.ISFAHAN)


